manifest:
  remotes:
    - name: papataku
      url-base: https://github.com/papataku
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: v0.3.0
      import: app/west.yml
    - name: z40-zmk-module
      remote: papataku
      revision: main
  self:
    path: config
